### ISSUE TITLE
source of library asset for unfolding

### ISSUE THREAD

**Issue by jeremydouglass** [g-otn/UCSDUnfoldingMaps#1]
One of the dependencies for this project listed in the classpath is: `unfolding.0.9.7-uscd.jar`

Is that a custom build of UnfoldingMaps? Where did it come from, and how was it made? (I can see the jar in the release -- although not in the repo -- but I'm wondering about its source).

**Comment by g-otn** [comment]
Hello! The `unfolding.0.9.7-uscd.jar` dependency comes from within the project `.zip` provided by the course throughout its modules. 

If I recall they do not go into details about the dependencies (where did it come from or how they were made), but I believe it's a custom build because of the logs when starting the application, I may try to find something about this in the course videos.

A regular UnfoldingMaps build may work too, but I haven't tried it.

The `.zip` also contains the other dependencies `.jar`s. I may commit the dependencies so it's easier to run the project.

**Comment by jeremydouglass** [comment]
Thanks so much! Yes, I think committing the dependencies could be helpful.

Re:custom maps jar, I could always reach out to the instructor--is the course code/year/instructor name referenced somewhere?

**Comment by g-otn** [comment]
I added the missing libraries at [`lib/`](https://github.com/g-otn/UCSDUnfoldingMaps/tree/master/lib) on 793cd9ce38a28e295df053d3395052bbd9251115.

Looking through the course, I found that the starter code for the course project is also available, besides the `.zip` file, in a [GitHub repo](https://github.com/cjalvarado/Course1StarterCode)! So maybe you can ask about the source code of that library in there.
They say the last update to the starter code was in August 2017, but maybe you can reach out to the repo owner?

Here's the [link](https://www.coursera.org/learn/object-oriented-java/supplement/VLwq0/setting-up-unfolding-maps) to the course notes where I found this info, however you can only access it if you have access to the course.

You can find information about the instructors and other course info at the [course page](https://www.coursera.org/learn/object-oriented-java#instructors).

**Comment by jeremydouglass** [comment]
Thank you so much again.
